name: CI with django

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/s etup-python@v2

      with:
        python-version: ${{ matrix.python-version }}
    - name: install Dependencies
      run: |
        python -m install --ugrade pip
        pip install -r requirements.txt
    - name: Lint with flake8
      run: |
        pip install flake8
        flake8
    - name: Coverage report
      run: |
        pip install coverage
        coverage run manage.py test
        coverage report
    - name: Django test
      run: |
        python3 manage.py test







